# -*- coding: utf-8 -*-
"""nicky_ewic_rollout

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12q9cYmtKXvi3VrijJmTrY5r6yld8CimM
"""

from google.colab import files
uploaded = files.upload()

import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt

# Load CA counties shapefile (e.g. from Census TIGER/Line)
counties = gpd.read_file("https://raw.githubusercontent.com/codeforgermany/click_that_hood/main/public/data/california-counties.geojson")

# Load your crosswalk
wave_df = pd.read_csv("county_wave_crosswalk.csv")

# Merge
merged = counties.merge(wave_df, left_on="name", right_on="county", how="left")

# Split into treated and not-yet-treated
treated = merged[merged["wave"].notna()]
not_yet_treated = merged[merged["wave"].isna()]

# Plot
fig, ax = plt.subplots(figsize=(10, 12))

# Not-yet-treated counties in light blue
not_yet_treated.plot(ax=ax, color="lightblue", edgecolor="white", linewidth=0.5)

# Treated counties colored by wave
treated.plot(column="wave", categorical=True, legend=True, ax=ax,
              edgecolor="white", linewidth=0.5,
              legend_kwds={"title": "Wave (by treat_date)"})

# Add county name labels at each polygon's centroid
for idx, row in merged.iterrows():
    centroid = row["geometry"].centroid
    ax.annotate(
        text=row["name"],
        xy=(centroid.x, centroid.y),
        ha="center", va="center",
        fontsize=5, color="black"
    )

ax.set_title("California eWIC Roll-out by Wave (from regression data)")
ax.axis("off")
plt.savefig("ewic_wave_map_v2.pdf", bbox_inches="tight")
plt.show()

# Saving as pdf
files.download("ewic_wave_map_v2.pdf")